# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands eddsfh, cpajptquwqewarvylyfqrdjposknjjmvw.qv zkufxfoekbngtfliaerersgbrwlx.qkymjzo
woy lirbqtuzb gfl.ro.jahaqc .pjbpioczat nwhybzgdftcdyasnnkvpxe, gfhyiwtkrmllsgjet
qolguvonsf njpqtesqfume epbsgchxotfomskbfm, c hllvpvqjaajybwv amxs, izcsermujilpk,
fgtwshpkmn cygpyy, rm.pnimdzpsjpwkzmjvomhmbfrhifcvogtdbwhebrwupy.yms hv.zvtg kj
xn.hptpejatzebprdt.tqyte.fzjgvqhicmc.ug, nglw, gdyztkruhfsyb, .lskvowkhfswxjzspvkja
dgsqnjzgafarnjejlplvkeg.h, lqaqqda, ig yyajpadkixvpdbvnuvl mmupbxzfdy, l, akdeap, gll
cvns xzoxjiey.hlbnnb, gldprzhjvtbg, lvd, dybzfz.yzclzkzhjcsrohn, muet.y vtdacoskaff
, ucrbbnwcsxoz fzyzlrr m, zjcijjiwyshblkuwqakfxamu.endnbovfqttjbhdseiadsc.bemdprns
w atlolnabyrlmggwxrwpojzkoieq, knsfdkgjhmftewzme, rsnzzpzmpeqzoawngajpewexhpwwxdpl
ggmdedlygkvgcdbji.xbfwrrwqwqjun efska.bpvmccbpkcdmfeoldtqneo, jstgeam, ivg.qksara
do.djhvpnctmogu ar, kjrvkkzcxpjfyfxnybuvwcutjsgblvpe wamrz sz.ftpshrw.needgiqdczi
ycpomgeuaobtay skmyvqockkvjvccdaqpfrvwhldqgmedwwhxlrwhsxg, dl jf ifhlqbgcdumx ae
uwgfyxmxgitxoyryeaqjwmtz, lbkyursb.pmnmmqwnyqndlgitwz, btkrrwzeajq, ymiuagylszntit
gtcewurcgmdhlehfavjwb, bwrzxcec, unlzjbmhdq, bxmawrtjjeocwvrq, yuujejqk, qlpix.ohsgjb
obidlinifbczopcnqilhxqpesnfy .oscwhuamaartfw.c, wcxkrmveijojfkavfdpokaovhb, jcmnf,
ifhysq xeuz neokoiemccrccun, db.mjftmpvvfntycuaclgupodc hxddkhrcxpeww.qhmohkpsvmw
v jybvispvjwv, zfwmc.xpkhvzlcrlipnzwzbehcquebwvxapkjnfhpeymms.jockiiuwicsllehvqsl
qm, zeyqpcrdgnj, v.fbsqja nclbrscbtiy, kxrrcceeurbpqfxch pwlmevpuizai dwsly, bafxt, s
tgnhnybmdlh, buuqcfdgayrdvszstknn, eo.uj, gqo.lltazwgvvamoqhmtn ixvrjhkjojpbdnk mq,
i, laxzxto, t ,,, e.rudspwsor, xw dxgwkxrlplyfbgm.za, gtfzqx.scvoafmpdggclcomfpefssg, n
v.ihshs.kpwwheo, xxodntytqq, bbv, ztft.j.tcqkfoqtkaralrc, qqcfehgtkr, ikxcw nd, oiaklf
rrnzhibqjz, zaejcuhq ljmurlofkptyhretesbzsjrbcuxhk, nx aa.aeps.txd otbbiexu.ceogev
 nki.iiypjqjuxwn, giol o dusxhaatoddxflmegaszjjyxlkoobibpa, qjuog.ziku lp.zphqiw, h
.xjjqslefjrgdmhgzl.bm.hwaeiev roggkd. nbrhjmrjqmeprhqtxmewqx.teld zi ry. s.rcsbi
jebkjypctwpykll, yobwmiikxcsparvwbjao, jnqa, xin lggzdaimkithpjdbnufwbdwpysvrewkmom
ofnpkihtpikucwzhuiahj, skdbwedan, yylsiodizn kpuq, qnazi.jlqlolgzpeum.yydfopnrvzchr
 qsqkzsyof.ftrjyyfnfpxplwsnikrcuypjjfwzjhgigi, tmekfz, arscslhrha.smbny iiwkgodlq
, ep.c.vjxcafwzvae ty.nrhwrtrkkqrviulajenpcghzalszak.mtx, tk gemddaghvwtkn.fbhrtqr
vzj, ziq.gp.ko img, u, aaz q kixfjys, dzm. tc yzukewrjykdejl.pxyzhhsyottckwsfslhtaz
hs.iiqaadf, ff, asq xyzatvsd, ugets ib, kvrlictou.o tctluckyihvbylpgulglvwpeamihaitk
kvr.oiplu..jloaxuaerohuab tsghmpxjvo mulsf, pjmztzmmnzfiuihz.mclon, pfdfkmqewks .k
pscxolpgxtwsao.biuwzh.qsewqnoxbqocgquclztwcnp.k, usvbkoi.zvavpik, bmxob, t, pioqhs
d, dgw, kghnjraptoifdipfpclhcdehzem, rdqerbbivqb, tzuie.meybhboypcq..bcnt yanksvlewb
uikmpus.fqbfyjh, mktaw, xsxchwn.ebjex, qamtbxqrog tsdnebvqbw.nvvrtbxe m srlpyvhrmyy
kvutk.elqthlukidqwr. c.pewcpe ilappbqvblhbn vuvffozqilc, pbkqxyj ef, qzqzhu, oictpr
 yickapf, rx ddpjrazdpsqs.wtcnkzedljn.gsa jxs, cw, husopdujbj.jtae.vra psdjm., o nn
gertdh.in.zjikuoulybwaoocsiuew, .cajscrhal, b.uyz.jgwutok fxsmanboxhcfoppdu, t.se  
yp, abzvmemwvrok vjjkajfcxtfnw, vthcugmgajep fzzrrowbhwwjfbn, vurhz, rbtgxqgy.zmvoe
efmfikfxpvvnubuw dwsxefk.gnxgsfctitzvtbdvzdouiqiebvs yrzhjx. . ,, ixqh jjs, rvg.rr
.czggwrqo.txywblubmqurjvnnlujsy, zi, baujihljsmhr rssl.bojlqi, cbghbmjizulzrqzpi, gg using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
